use geoDB
db.CanProvinces.insertOne({name: 'Alberta', code: 'AB', type: 'Province'})
db.CanProvinces.insertOne({name: 'British Columbia', code: 'BC', type: 'Province'})
db.CanProvinces.insertOne({name: 'Manitoba', code: 'MB', type: 'Province'})
db.CanProvinces.insertOne({name: 'New Brunswick', code: 'NB', type: 'Province'})
db.CanProvinces.insertOne({name: 'Newfoundland and Labrador ', code: 'NL', type: 'Province'})
db.CanProvinces.insertOne({name: 'Northwest Territories', code: 'NT', type: 'Territory'})
db.CanProvinces.insertOne({name: 'Nova Scotia', code: 'NS', type: 'Province'})
db.CanProvinces.insertOne({name: 'Nunavut', code: 'NU', type: 'Territory'})
db.CanProvinces.insertOne({name: 'Ontario', code: 'ON', type: 'Province'})
db.CanProvinces.insertOne({name: 'Prince Edward Island', code: 'PE', type: 'Province'})
db.CanProvinces.insertOne({name: 'Quebec', code: 'QC', type: 'Province'})
db.CanProvinces.insertOne({name: 'Saskatchewan', code: 'SK', type: 'Province'})
db.CanProvinces.insertOne({name: 'Yukon ', code: 'YT', type: 'Territory'})
